name: Flowgramming Build
on:
    push:
        branches:
            - main
jobs:
    release:
        name: Build and deploy site
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.3

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - name: Install npm dependencies
              run: npm ci

            - name: Build
              run: npm run gulp

            - name: Post Deploy
              run: npm run clean

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: './'
